# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terracove < Formula
  desc ""
  homepage "https://github.com/jatalocks/terracove"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.3/terracove_0.0.3_Darwin_arm64.tar.gz"
      sha256 "6bc2eef704b5d1f9221aa93daea3d0d23eeae39b8a6090d020f4c792cad101e2"

      def install
        bin.install "terracove"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.3/terracove_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "d6f0f1ccab148b659fd960c297615e628c00d759c81fb2484712d46a63a8bcfd"

      def install
        bin.install "terracove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.3/terracove_0.0.3_Linux_x86_64.tar.gz"
      sha256 "bdcadafed958dc3bacc5bf0b454b1256a198bc1bb7bf6580b59ff5fb0a8a390d"

      def install
        bin.install "terracove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.3/terracove_0.0.3_Linux_arm64.tar.gz"
      sha256 "a6cdf2271a4cc71df4611a394c58d1c8f83724c5e6706a361a3258fdc4add281"

      def install
        bin.install "terracove"
      end
    end
  end
end
