# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terracove < Formula
  desc ""
  homepage "https://github.com/jatalocks/terracove"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.1/terracove_0.0.1_Darwin_arm64.tar.gz"
      sha256 "1bb4aad2a95b40dee5560b6709de9034fbd44471b2b1fe1191bc3c80a02b534e"

      def install
        bin.install "terracove"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.1/terracove_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "45c43ffcc62871b87995b361536bb29f6f47ca75f97fcaf26e0df7804115deb3"

      def install
        bin.install "terracove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.1/terracove_0.0.1_Linux_x86_64.tar.gz"
      sha256 "99fe212b81f53caf41339dadd03d809bbad470d96523c160f11bbb7eea22e6c8"

      def install
        bin.install "terracove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.1/terracove_0.0.1_Linux_arm64.tar.gz"
      sha256 "94a62c99acee54e2626a8367d9a9cfb48a08e1ea3f74c8a534c61be549cde0a7"

      def install
        bin.install "terracove"
      end
    end
  end
end
