# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terracove < Formula
  desc ""
  homepage "https://github.com/jatalocks/terracove"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.1/terracove_0.0.1_Darwin_arm64.tar.gz"
      sha256 "91c04b498d0735961efd9cbd1dacf0dadc211f564d958044e5ac1c52cbdc6c80"

      def install
        bin.install "terracove"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.1/terracove_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "b95866b59b5d3ad6c3ea9d5216ea01086194348b5328b80f1de490bcdd337735"

      def install
        bin.install "terracove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.1/terracove_0.0.1_Linux_arm64.tar.gz"
      sha256 "880a1f0f8aa7f49d7420f0e09de0f304eb20869a395afa233c34981a25c6120b"

      def install
        bin.install "terracove"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jatalocks/terracove/releases/download/v0.0.1/terracove_0.0.1_Linux_x86_64.tar.gz"
      sha256 "e45ace9630a8d125af0385d9940e2e23a3a70fb9ca1e0e3fa542299208ecc419"

      def install
        bin.install "terracove"
      end
    end
  end
end
